apiVersion: apps/v1
kind: Deployment
# Deployment will maintain Replica Set
# Replica Set will maintain Num of Pod

metadata:
  name: rest-api
  namespace: default # it should "roadrunner" in real case
  labels:
    app: rest-api
    desc: golang_rest_api

  
    
spec:
  replicas: 1 
  # Make sure we have num of pod  
  selector:
    # Watching num of pod in selected pod label  
    matchLabels:
      name: rest-api
  template:
    # Template for pod
    metadata:
      name: rest-api
      # Replica set will add random char suffix  
      labels:
        name: rest-api
        app: rest-api
        # We watch this "name" label for service and replica set
    spec:
      # serviceAccountName: golang-app
      containers:
        - name: rest
          image: iimnd/golang-app:2.0.2 # versi 3 oprekan baru opentracing
          ports:
            # Use standard 8000 port for all system as much as possible
            - containerPort: 8000
          # resources:
          #  # Give appropriate number
          #   requests:
          #     memory: "32Mi" 
          #     cpu: "200m"
          #   limits:
          #     memory: "64Mi"
          #     cpu: "250m"
          volumeMounts:
          - name: golang-volume-2
            mountPath: /app/.env
            subPath: .env
          env:
            # Inject POD spec
            - name: POD_NAME
              # value: your_value
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name


      volumes:
      - name: golang-volume-2
        configMap:
         name: golang-app-env-2


# ---
# apiVersion: v1
# kind: ServiceAccount
# metadata:
#   name: golang-app
#   labels:
#     account: golang-app
