apiVersion: v1
kind: Service
metadata:
  name: rest-api-service
  namespace: default # it should "roadrunner" in real case
  labels:
    app: rest-api
    service: rest-api
    desc: testing_app
   
spec:
  type: NodePort
  selector:
    name: rest-api
    app: rest-api
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
      name: http2
      # Target to Pod port

